Repository fesi3/WeMo-FE, pull requests merged in 2025-02, with the labels that each got.

#122 [Fix] 전역객체 초기화 시 유저 정보 유실 문제
  package.json
  src/components/gnb/footer/index.tsx
  src/components/gnb/header/index.tsx
  src/components/gnb/spinner/index.tsx
  src/components/shared/layout/GNB.tsx
  src/constants/gnb.ts
  src/hooks/useAuth.tsx
  src/hooks/useFetchDataFromKey.ts
  src/pages/_app.tsx
  src/redux/store.ts
  yarn.lock
Labels: Fix

#123 [Refac] oAuth 로그인 로직 hook 생성 / 회원가입, 로그인 폼 디바운스 적용
  package.json
  src/api/axiosInstance.ts
  src/components/auth/login/findInfo/index.tsx
  src/components/auth/login/loginBanner/index.tsx
  src/components/auth/login/loginForm/index.tsx
  src/components/auth/signup/signupForm/index.tsx
  src/components/plans/RenderCommonContent.tsx
  src/components/shared/input/HOC/withError.tsx
  src/constants/apiPath.ts
  src/constants/gnb.ts
  src/hooks/useLoginForm.tsx
  src/hooks/useOAuthLogin.tsx
  src/hooks/useSignupForm.tsx
  src/pages/login/oauth2/callback/google/index.tsx
  src/pages/login/oauth2/callback/kakao/index.tsx
  src/pages/login/oauth2/callback/naver/index.tsx
  src/pages/signup/index.tsx
  src/pages/start/index.tsx
  yarn.lock
Labels: Feat, Refactor

#128 [Refactor] 무한스크롤(커서기반) 로직 리펙토링
  src/hooks/useCursorInfiniteScroll.tsx
  src/pages/plans/index.tsx
Labels: Refactor

#131 [Refacotr] UI 수정
  src/assets/icons/emptyHeart.svg
  src/assets/icons/heart.svg
  src/components/plans/Greeting.tsx
  src/components/plans/RenderCommonContent.tsx
  src/components/plans/SubCategoryFilter.tsx
  src/components/plans/card/Card.tsx
  src/components/plans/card/CardList.tsx
  src/pages/plans/index.tsx
Labels: Design

#135 [Feat] 일정 목록 "좋아요", 찜한 모임 axios instance 적용하여 쿠키 기반 인증 구현
  src/components/plans/LikeButton.tsx
  src/components/plans/RenderCommonContent.tsx
  src/hooks/useCursorInfiniteScroll.tsx
  src/pages/saved-gathering/index.tsx
  src/pages/savedGathering/index.tsx
Labels: Feat

#138 [GHA] 버셀을 활용한 CD 구축 및 PR 내용 초기화 CI 수정
  .github/workflows/wemo-cd.yml
  .github/workflows/wemo-ci.yml
  build.sh
Labels: Fix, Docs

#140 [Fix] cd 오류로 인한 토큰 수정
  .github/workflows/wemo-cd.yml
  .github/workflows/wemo-ci.yml
Labels: Fix

#156 [Feat] 모임 목록 페이지 react query 적용
  src/api/fetchMeetings.ts
  src/components/meetings/MeetingsSortDropdown.tsx
  src/components/meetings/card/Card.tsx
  src/components/meetings/card/CardList.tsx
  src/components/meetings/dropdown/CategoryDropdown.tsx
  src/hooks/useCursorInfiniteScrollPlans.tsx
  src/hooks/useMeetingsQuery.ts
  src/hooks/useScrollObserver.ts
  src/pages/meetings/index.tsx
  src/pages/plans/index.tsx
  src/types/api/meetingList.ts
Labels: Feat

#162 [Refactor] 일정 목록 페이지 UI 수정
  src/components/gnb/header/index.tsx
  src/components/plans/LikeButton.tsx
  src/components/plans/RenderCommonContent.tsx
  src/components/plans/RenderTabContent.tsx
  src/components/plans/card/Card.tsx
  src/hooks/useHeaderHeight.ts
  src/pages/plans/index.tsx
Labels: Refactor

#166 [Refactor] QA 사항 반영
  src/components/meetings/card/Card.tsx
  src/components/meetings/card/CardList.tsx
  src/components/meetings/dropdown/CategoryDropdown.tsx
  src/components/plans/LikeButton.tsx
  src/components/plans/RenderCommonContent.tsx
  src/components/plans/RenderTabContent.tsx
  src/components/plans/card/Card.tsx
  src/components/plans/editMeeting/CreateMeetingButton.tsx
  src/components/plans/tab/Tabs.tsx
  src/components/shared/calendar/CalendarPicker.tsx
  src/components/shared/calendar/DateModal.tsx
  src/components/shared/dropdown/RegionDropdown.tsx
  src/pages/all-reviews/index.tsx
  src/pages/meetings/index.tsx
  src/pages/plans/index.tsx
  src/pages/saved-gathering/index.tsx
  src/styles/globals.css
Labels: Refactor

#167 [fix] 오어스 로그인 버그 수정
  src/components/gnb/header/index.tsx
  src/constants/gnb.ts
Labels: Fix
