Repository fesi3/WeMo-FE, pull requests merged in 2025-01, with the labels that each got.

#9 Feature/#6 modal component
  src/components/shared/modals/ModalBackDrop.tsx
  src/components/shared/modals/ModalFrame.tsx
  src/components/shared/modals/ModalPortal.tsx
  src/hooks/useModal.tsx
  src/pages/_document.tsx
  src/pages/index.tsx
  src/styles/globals.css
Labels: Feat

#11 chore: tailwindCSS 클래스 자동정렬 pritter 플러그인 설치
  .prettierrc
  package.json
  yarn.lock
Labels: Chore

#42 [Setting] 폰트, 색상 tailwind 설정 추가
  src/pages/_document.tsx
  src/pages/login/index.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: Style

#41 [Feature] 카테고리 선택 탭 구현, 애니메이션 적용
  package.json
  src/components/findGatherings/tab/tab.tsx
  src/pages/index.tsx
  src/pages/meetings/index.tsx
  yarn.lock
Labels: Feat

#50 [Setting] .env 파일 생성 / axios instance 생성 / 리액트 쿼리에 사용할 패칭함수 제작
  .gitignore
  src/api/axiosInstance.ts
  src/api/fetchData.ts
Labels: Feat

#71 [Feature] 찜한 모임 페이지 구현
  public/assets/like-page-heart.png
  src/hooks/useCursorInfiniteScroll.tsx
  src/hooks/usePageInfiniteScroll.ts
  src/pages/liked/index.tsx
  src/pages/meetings/index.tsx
Labels: Feat

#105 [Fix] GNB rendering issue
  src/hooks/useAuth.tsx
Labels: !HOTFIX

#115 [Fix] login page form validation logic 수정
  src/components/auth/login/findInfo/index.tsx
  src/components/auth/login/loginBanner/index.tsx
  src/components/auth/login/loginForm/index.tsx
  src/components/shared/input/HOC/withError.tsx
  src/components/shared/input/index.tsx
  src/hooks/useLoginForm.tsx
  src/pages/login/index.tsx
  src/pages/start/index.tsx
Labels: Fix
